// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Repositories;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WebApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 175m,
                            Title = "Cinsiyet Belası"
                        },
                        new
                        {
                            Id = 2,
                            Price = 175m,
                            Title = "Kadınsız İnkılap"
                        },
                        new
                        {
                            Id = 3,
                            Price = 175m,
                            Title = "Tek Tanrılı Dinler Karşısında Kadın"
                        },
                        new
                        {
                            Id = 4,
                            Price = 175m,
                            Title = "Toplumsal Cinsiyet ve Bilim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
